class DataConstStrings:
    # ? keys
    id_key = "_id"
    is_active_key = "is_active"
    phone_key = "phone"
    auth_key = "auth"
    user_key = "user"
    users_key = "users"
    person_id_key = "person_id"
    person_key = "person"
    people_key = "people"
    inserted_id_key = "inserted_id"
    is_reach_the_dinner_key = "is_reach_the_dinner"
    existing_id_key = "existing_id"
    add_manual_key = "add_manual"
    
    table_key = "table"
    tables_key = "tables"
    table_id_key = "table_id"
    position_key = "position"
    
    user_id_key = "user_id"
    username_key = "username"
    email_key = "email"
    token_key = "token"
    exp_key = "exp"
    password_key = "password"
    user_data_key = "user"