class PersonDataConstStrings:
    id = "_id"
    is_active = "is_active"
    personal_number = "personal_number"
    phone = "phone"
    birthday = "birthday"
    military_discharge_date = "military_discharge_date"
    unavailable_dates = "unavailable_dates"
    role = "role"
    rank = "rank"
    guards_frequency = "guards_frequency"
    person_id = "person_id"
    person = "person"
    people = "people"
    inserted_id = "inserted_id"